### PR TITLE
Implicit conversion from Scala Function to MetricFilter.

### PR DESCRIPTION
**Pull request by maciej**
Hey,
I've added an implicit conversion from a Scala Function to a MetricFilter.

@erikvanoosten what do you think about that?

### CODE REVIEW

**Comment by erikvanoosten** [comment]
Nice!

Would you like to write some documentation and tests also?

**Comment by maciej** [comment]
Sure. The method is trivial, but tests might be useful to guard from regressions.

**Comment by erikvanoosten** [comment]
Hi @maciej, are you still interested in writing docs and tests?

**Comment by maciej** [comment]
Hi @erikvanoosten, yes! I was even wondering why you haven't looked at the PR after I updated it with tests. Let me write the docs sometime next week and I'll update it!

**Comment by erikvanoosten** [comment]
O wow, that is silly. I had not noticed that. Sorry for that. I'll take a look tomorrow. Thanks!

**Comment by erikvanoosten** [comment]
I guess we need two tests. One tests that implicit conversion works (if it compiles it's already good), the other tests that the function is called when you call the wrapper. The latter could be done with a mock.
There is no need to test anything from metrics-core.

**Comment by erikvanoosten** [comment]
BTW, don't hurry. I'll be off the grid for some time

**Comment by maciej** [comment]
Hey @erikvanoosten! I've added the second test you asked for. I'm not sure where to mention it in the documentation, though.

**Comment by erikvanoosten** [comment]
Hi @maciej , could you please review my changes? They're in commit 188aa89f345e100364eeffdb81a5941fbc8bc6a1. Thanks!

**Comment by maciej** [comment]
@erikvanoosten changes look great! I have to say you write great documentation! Thanks you for your help with completing this PR!

**Comment by erikvanoosten** [comment]
Thanks for your kind words @maciej. I'll try to find some time to release 3.5.1 next weekend.

**Pull request merged**
